AWSTemplateFormatVersion: '2010-09-09'
Description: 'Database resources for ECS-EC2-Jenkins-Git infrastructure'

Parameters:
  ProjectName:
    Type: String
    Description: Project name used for resource tagging
  
  Environment:
    Type: String
    Description: Deployment environment
  
  # VpcId parameter removed as it's not used
  
  DatabaseSubnetIds:
    Type: String
    Description: Comma-separated list of database subnet IDs
  
  DBSecurityGroupId:
    Type: String
    Description: Database security group ID
  
  DBEngine:
    Type: String
    Default: postgres
    AllowedValues: [postgres, mysql]
    Description: Database engine
  
  DBEngineVersion:
    Type: String
    Default: 15.4
    Description: Database engine version
  
  DBInstanceClass:
    Type: String
    Default: db.t3.small
    Description: Database instance class
  
  DBAllocatedStorage:
    Type: Number
    Default: 20
    Description: Allocated storage for database in GB
  
  DBMaxAllocatedStorage:
    Type: Number
    Default: 100
    Description: Maximum allocated storage for database in GB
  
  DBName:
    Type: String
    Default: appdb
    Description: Name of the database
  
  DBUsername:
    Type: String
    Default: dbadmin
    Description: Username for the database
  
  DBPort:
    Type: Number
    Default: 5432
    Description: Port for the database
  
  # DBMultiAZ parameter removed as we force MultiAZ to true
  
  EnablePerformanceInsights:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    Description: Enable Performance Insights

Resources:
  # KMS Key for Secrets Manager
  DBSecretsKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub KMS key for ${ProjectName}-${Environment} database secrets
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - kms:Create*
              - kms:Describe*
              - kms:Enable*
              - kms:List*
              - kms:Put*
              - kms:Update*
              - kms:Revoke*
              - kms:Disable*
              - kms:Get*
              - kms:Delete*
              - kms:ScheduleKeyDeletion
              - kms:CancelKeyDeletion
            Resource: '*'
          - Sid: Allow Secrets Manager to use the key
            Effect: Allow
            Principal:
              Service: secretsmanager.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:GenerateDataKey*
            Resource: '*'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
  
  # KMS Key Alias
  DBSecretsKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${ProjectName}-${Environment}-db-secrets-key
      TargetKeyId: !Ref DBSecretsKMSKey
  
  # Generate random password for database
  DBPasswordSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '/${ProjectName}/${Environment}/db-password'
      Description: !Sub 'Database password for ${ProjectName}-${Environment}'
      KmsKeyId: !Ref DBSecretsKMSKey
      GenerateSecretString:
        SecretStringTemplate: '{"username": "dbadmin"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-db-password'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # Create DB Subnet Group
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub '${ProjectName}-${Environment}-db-subnet-group'
      DBSubnetGroupDescription: !Sub 'DB subnet group for ${ProjectName}-${Environment}'
      SubnetIds: !Split [',', !Ref DatabaseSubnetIds]
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-db-subnet-group'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # Create DB Parameter Group for PostgreSQL
  PostgreSQLParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Condition: IsPostgreSQL
    Properties:
      Description: !Sub 'Parameter group for ${ProjectName}-${Environment} PostgreSQL'
      Family: 'postgres15'
      Parameters:
        max_connections: '100'
        shared_buffers: '16384'
        log_statement: 'all'
        log_min_duration_statement: '1000'
        # SSL configuration
        ssl: 'true'
        ssl_min_protocol_version: 'TLSv1.2'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-pg'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # Create DB Parameter Group for MySQL
  MySQLParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Condition: IsMySQL
    Properties:
      Description: !Sub 'Parameter group for ${ProjectName}-${Environment} MySQL'
      Family: 'mysql8.0'
      Parameters:
        max_connections: '100'
        slow_query_log: '1'
        long_query_time: '1'
        general_log: '0'
        # SSL configuration
        require_secure_transport: '1'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-pg'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # Create Option Group for MySQL
  MySQLOptionGroup:
    Type: AWS::RDS::OptionGroup
    Condition: IsMySQL
    Properties:
      EngineName: mysql
      MajorEngineVersion: !Select [0, !Split ['.', !Ref DBEngineVersion]]
      OptionGroupDescription: !Sub 'Option group for ${ProjectName}-${Environment} MySQL'
      OptionConfigurations:
        - OptionName: MARIADB_AUDIT_PLUGIN
          OptionSettings:
            - Name: SERVER_AUDIT_EVENTS
              Value: CONNECT,QUERY
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-og'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # Enhanced Monitoring IAM Role
  RDSMonitoringRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-rds-monitoring-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: monitoring.rds.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-rds-monitoring-role'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # RDS DB Instance
  DBInstance:
    Type: AWS::RDS::DBInstance
    Metadata:
      checkov:
        skip:
          - id: CKV2_AWS_69
            comment: "SSL encryption is enforced through parameter groups and custom resources. PostgreSQL uses ssl=true and ssl_min_protocol_version=TLSv1.2, MySQL uses require_secure_transport=1. Additionally, we use a custom Lambda that checks and enforces SSL."
    Properties:
      DBInstanceIdentifier: !Sub '${ProjectName}-${Environment}-db'
      Engine: !Ref DBEngine
      EngineVersion: !Ref DBEngineVersion
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      MaxAllocatedStorage: !Ref DBMaxAllocatedStorage
      StorageType: gp3
      StorageEncrypted: true
      KmsKeyId: !Ref DBSecretsKMSKey
      DBName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DBPasswordSecret}::password}}'
      Port: !Ref DBPort
      VPCSecurityGroups:
        - !Ref DBSecurityGroupId
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBParameterGroupName: !If [IsPostgreSQL, !Ref PostgreSQLParameterGroup, !Ref MySQLParameterGroup]
      OptionGroupName: !If [IsMySQL, !Ref MySQLOptionGroup, !Ref 'AWS::NoValue']
      UseDefaultProcessorFeatures: true 
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      PubliclyAccessible: false
      # Force MultiAZ to be true
      MultiAZ: true
      # Enable IAM Authentication
      EnableIAMDatabaseAuthentication: true
      BackupRetentionPeriod: !If [IsProd, 30, 7]
      DeletionProtection: !If [IsProd, true, false]
      EnablePerformanceInsights: !Ref EnablePerformanceInsights
      PerformanceInsightsKMSKeyId: !Ref DBSecretsKMSKey
      PerformanceInsightsRetentionPeriod: 7
      MonitoringInterval: 60
      MonitoringRoleArn: !GetAtt RDSMonitoringRole.Arn
      EnableCloudwatchLogsExports: !If 
        - IsPostgreSQL
        - ['postgresql', 'upgrade']
        - ['audit', 'error', 'general', 'slowquery']
      CopyTagsToSnapshot: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-db'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # Store database credentials in Secrets Manager
  DBCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '/${ProjectName}/${Environment}/database'
      Description: !Sub 'Database credentials for ${ProjectName} ${Environment}'
      KmsKeyId: !Ref DBSecretsKMSKey
      SecretString: !Join 
        - ''
        - - '{"username":"'
        - !Ref DBUsername
        - '","password":"'
        - !Sub '{{resolve:secretsmanager:${DBPasswordSecret}::password}}'
        - '","engine":"'
        - !Ref DBEngine
        - '","host":"'
        - !GetAtt DBInstance.Endpoint.Address
        - '","port":"'
        - !GetAtt DBInstance.Endpoint.Port
        - '","dbname":"'
        - !Ref DBName
        - '","url":"'
        - !Ref DBEngine
        - '://'
        - !Ref DBUsername
        - ':'
        - !Sub '{{resolve:secretsmanager:${DBPasswordSecret}::password}}'
        - '@'
        - !GetAtt DBInstance.Endpoint.Address
        - ':'
        - !GetAtt DBInstance.Endpoint.Port
        - '/'
        - !Ref DBName
        - '"}'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-db-credentials'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
  
  # Custom Lambda for enforcing SSL on RDS
  RDSSSLEnforcerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: RDSModifyInstance
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - rds:DescribeDBInstances
                  - rds:ModifyDBInstance
                Resource: !Sub 'arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:${ProjectName}-${Environment}-db'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-rds-ssl-enforcer-role'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
  
  # SNS Topic for Lambda Dead Letter Queue
  RDSSSLEnforcerDLQTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub '${ProjectName}-${Environment}-rds-ssl-enforcer-dlq'
      TopicName: !Sub '${ProjectName}-${Environment}-rds-ssl-enforcer-dlq'
      KmsMasterKeyId: !Ref DBSecretsKMSKey
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
  
  # Security group for Lambda function
  RDSSSLEnforcerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS SSL enforcer Lambda function
      VpcId: !ImportValue 
        !Sub '${ProjectName}-${Environment}-vpc-id'
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: HTTPS egress for AWS API access
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
  
  RDSSSLEnforcerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-rds-ssl-enforcer'
      Handler: index.handler
      Role: !GetAtt RDSSSLEnforcerRole.Arn
      Runtime: python3.12
      Timeout: 300
      ReservedConcurrentExecutions: 5
      DeadLetterConfig:
        TargetArn: !Ref RDSSSLEnforcerDLQTopic
      KmsKeyArn: !Ref DBSecretsKMSKey
      VpcConfig:
        SecurityGroupIds:
          - !Ref RDSSSLEnforcerSecurityGroup
        SubnetIds: !Split 
          - ','
          - !ImportValue 
            !Sub '${ProjectName}-${Environment}-private-subnets'
      Code:
        ZipFile: |
          import json
          import boto3
          import cfnresponse
          import time
  
          def handler(event, context):
              responseData = {}
  
              if event['RequestType'] == 'Delete':
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
                  return
  
              try:
                  db_identifier = event['ResourceProperties']['DBInstanceIdentifier']
                  region = event['ResourceProperties']['Region']
  
                  # Initialize RDS client
                  rds = boto3.client('rds', region_name=region)
  
                  # Wait for RDS instance to be available
                  for _ in range(30):  # Try for 5 minutes (10 seconds * 30)
                      try:
                          response = rds.describe_db_instances(DBInstanceIdentifier=db_identifier)
                          status = response['DBInstances'][0]['DBInstanceStatus']
                          if status == 'available':
                              break
                      except Exception as e:
                          print(f"Error checking DB status: {e}")
                      time.sleep(10)
  
                  # Modify the DB instance to require SSL connections
                  rds.modify_db_instance(
                      DBInstanceIdentifier=db_identifier,
                      CertificateRotationRestart=False
                  )
  
                  responseData['Message'] = "Modified RDS instance to enforce SSL"
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
              except Exception as e:
                  print(f"Error: {e}")
                  responseData['Error'] = str(e)
                  cfnresponse.send(event, context, cfnresponse.FAILED, responseData)
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-rds-ssl-enforcer'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
  
  # Custom resource to enforce SSL
  EnforceRDSSSL:
    Type: Custom::EnforceRDSSSL
    DependsOn: DBInstance
    Properties:
      ServiceToken: !GetAtt RDSSSLEnforcerFunction.Arn
      DBInstanceIdentifier: !Ref DBInstance
      Region: !Ref AWS::Region

Conditions:
  IsPostgreSQL: !Equals [!Ref DBEngine, 'postgres']
  IsMySQL: !Equals [!Ref DBEngine, 'mysql']
  IsProd: !Equals [!Ref Environment, 'prod']

Outputs:
  DBEndpoint:
    Description: Database endpoint address
    Value: !GetAtt DBInstance.Endpoint.Address
    Export:
      Name: !Sub '${ProjectName}-${Environment}-db-endpoint'

  DBInstanceId:
    Description: Database instance ID
    Value: !Ref DBInstance
    Export:
      Name: !Sub '${ProjectName}-${Environment}-db-instance-id'

  DBPort:
    Description: Database port
    Value: !GetAtt DBInstance.Endpoint.Port
    Export:
      Name: !Sub '${ProjectName}-${Environment}-db-port'

  DBSecretArn:
    Description: ARN of database credentials secret
    Value: !Ref DBCredentialsSecret
    Export:
      Name: !Sub '${ProjectName}-${Environment}-db-secret-arn'