AWSTemplateFormatVersion: '2010-09-09'
Description: 'Database Read Replica Template for ECS-EC2-Jenkins-Git infrastructure'

Parameters:
  ProjectName:
    Type: String
    Default: ecs-jenkins-github
    Description: Project name used for resource tagging
  
  Environment:
    Type: String
    Default: dr
    Description: Deployment environment
  
  # VpcId parameter removed as it's not used
  
  DatabaseSubnets:
    Type: List<String>
    Description: List of database subnet IDs
  
  DBSecurityGroupId:
    Type: String
    Description: Security group ID for database access
  
  DBEngine:
    Type: String
    Default: postgres
    AllowedValues:
      - postgres
      - mysql
    Description: Database engine
  
  # DBEngineVersion parameter removed as it's not used
  
  DBInstanceClass:
    Type: String
    Default: db.t3.small
    Description: RDS instance class for the database
  
  PrimaryDBIdentifier:
    Type: String
    Description: Identifier of the primary database instance
  
  ReplicaBackupRetentionPeriod:
    Type: Number
    Default: 7
    Description: The number of days to retain backups of the read replica
    MinValue: 0
    MaxValue: 35
  
  # MultiAZ parameter removed as it was not used - Read Replica uses hardcoded MultiAZ: true

Conditions:
  IsPostgreSQL: !Equals [!Ref DBEngine, 'postgres']
  # IsMultiAZEnabled condition removed as it's not used

Resources:
  # DB Subnet Group
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub ${ProjectName}-${Environment}-db-subnet-group
      SubnetIds: !Ref DatabaseSubnets
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-db-subnet-group
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # Read replica for DR
  MonitoringRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: monitoring.rds.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-rds-monitoring-role
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
  
  DBReadReplica:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub ${ProjectName}-${Environment}-read-replica
      SourceDBInstanceIdentifier: !Ref PrimaryDBIdentifier
      DBInstanceClass: !Ref DBInstanceClass
      Engine: !Ref DBEngine
      PubliclyAccessible: false
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref DBSecurityGroupId
      MultiAZ: true
      BackupRetentionPeriod: !Ref ReplicaBackupRetentionPeriod
      EnablePerformanceInsights: true
      EnableIAMDatabaseAuthentication: true
      MonitoringInterval: 30
      MonitoringRoleArn: !GetAtt MonitoringRole.Arn
      # Note: StorageEncryption is inherited from the source DB instance
      # checkov:skip=CKV_AWS_16: Storage encryption is inherited from the primary DB instance
      CopyTagsToSnapshot: true
      EnableCloudwatchLogsExports: !If
        - IsPostgreSQL
        - ['postgresql', 'upgrade']
        - ['error', 'general']
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-read-replica
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: DR
          Value: true

  # SNS Topic for replication failures
  SNSTopicKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub 'KMS key for ${ProjectName}-${Environment} SNS topic encryption'
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow SNS Service
            Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action:
              - 'kms:GenerateDataKey*'
              - 'kms:Decrypt'
            Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-db-sns-kms'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
  
  SNSTopicKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/${ProjectName}-${Environment}-db-sns'
      TargetKeyId: !Ref SNSTopicKMSKey
  
  ReplicationFailuresTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${ProjectName}-${Environment}-replication-failures
      KmsMasterKeyId: !Ref SNSTopicKMSKey
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # RDS event subscription for replication failures
  RDSEventSubscription:
    Type: AWS::RDS::EventSubscription
    Properties:
      EventCategories:
        - availability
        - deletion
        - failover
        - failure
        - low storage
        - maintenance
        - notification
        - recovery
        - replication
      SnsTopicArn: !Ref ReplicationFailuresTopic
      SourceIds:
        - !Ref DBReadReplica
      SourceType: db-instance
      Enabled: true
      SubscriptionName: !Sub ${ProjectName}-${Environment}-replication-failures

Outputs:
  DBEndpoint:
    Description: Endpoint of the DR DB read replica
    Value: !GetAtt DBReadReplica.Endpoint.Address
  
  DBPort:
    Description: Port of the DR DB read replica
    Value: !GetAtt DBReadReplica.Endpoint.Port
  
  DBIdentifier:
    Description: Identifier of the DR DB read replica
    Value: !Ref DBReadReplica
  
  ReplicationFailureTopicArn:
    Description: ARN of the SNS topic for replication failures
    Value: !Ref ReplicationFailuresTopic